steps:
    - name: gcr.io/cloud-builders/docker
      args:
          [
              'build',
              '--build-arg',
              'DATABASE_URL',
              '--build-arg',
              'API_SERVER_URL',
              '--build-arg',
              'PORT=${_PORT}',
              '-t',
              '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE}:$COMMIT_SHA',
              '-f',
              './Dockerfile',
              '.',
          ]
      secretEnv: ['DATABASE_URL', 'API_SERVER_URL']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE}:$COMMIT_SHA']
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: gcloud
      args:
          [
              'run',
              'deploy',
              '${_SERVICE_NAME}',
              '--image',
              '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE}:$COMMIT_SHA',
              '--region',
              '${_LOCATION}',
              '--port',
              '${_PORT}',
          ]
availableSecrets:
    secretManager:
        - versionName: projects/${_PROJECT_ID}/secrets/DATABASE_URL/versions/latest
          env: DATABASE_URL
        - versionName: projects/${_PROJECT_ID}/secrets/API_SERVER_URL/versions/latest
          env: API_SERVER_URL
images:
    - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE}:$COMMIT_SHA'
